"""FastAPI application factory for the Traceability Store."""

import logging

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy import text

from src.api.routes import metrics_router, reports_router
from src.api.schemas import HealthResponse
from src.db.engine import get_engine, get_session_factory

logger = logging.getLogger(__name__)


def create_app() -> FastAPI:
    """Construct and configure the FastAPI application.

    Returns:
        A fully configured :class:`FastAPI` instance ready to serve requests.
    """
    app = FastAPI(
        title="SignalOps Traceability Store",
        description=(
            "Audit trail service for every digest generated by SignalOps. "
            "Stores reports, tool call logs, and source references. "
            "Exposes read/write endpoints for the Agent Orchestrator and Web App."
        ),
        version="0.1.0",
        docs_url="/docs",
        redoc_url="/redoc",
    )

    # Allow all origins for internal service-to-service communication.
    # Tighten this for public deployments.
    app.add_middleware(
        CORSMiddleware,
        allow_origins=["*"],
        allow_methods=["*"],
        allow_headers=["*"],
    )

    # Register routers
    app.include_router(reports_router)
    app.include_router(metrics_router)

    # ── Health check ───────────────────────────────────────────────────────
    @app.get(
        "/health",
        response_model=HealthResponse,
        tags=["health"],
        summary="Health check",
        description=(
            "Returns the health status of the service. "
            "Performs a live database connectivity check."
        ),
    )
    async def health() -> HealthResponse:
        """Verify the service is up and the database is reachable."""
        db_connected = False
        try:
            engine = get_engine()
            async with engine.connect() as conn:
                await conn.execute(text("SELECT 1"))
            db_connected = True
        except Exception:
            logger.exception("Health check: database connectivity failed")

        return HealthResponse(
            status="healthy" if db_connected else "unhealthy",
            db_connected=db_connected,
        )

    return app
